POST http://localhost:4004/dev-challenge/Tests(ID=05c25e01-a579-4c0c-88ca-55f8cb49dafc,IsActiveEntity=true)/DevChallengeService.assignQuestionsToTest
Content-Type: application/json 

{
  "questionsCount":3
} 
