POST http://localhost:4004/dev-challenge/Tests(ID=2853fe0f-e539-49c9-b821-b3034bb810f6,IsActiveEntity=true)/DevChallengeService.assignQuestionsToTest
Content-Type: application/json 

{
  "questionsCount":3
} 
