POST http://localhost:4004/dev-challenge/Tests(ID=15c25e09-6f51-46d3-859a-63b335b2605a,IsActiveEntity=true)/DevChallengeService.assignQuestionsToTest
Content-Type: application/json 

{
  "questionsCount":3
} 
